from __future__ import annotations
# Generated by Django 5.2.8 on 2026-02-24 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taxonomy", "0002_remove_category_taxonomy_ca_slug_79d2b3_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "key",
                    models.SlugField(
                        allow_unicode=True,
                        help_text="کلید ثابت برای ارجاع (مثلاً: markdown-superprompt)",
                        max_length=80,
                        unique=True,
                        verbose_name="کلید",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("description", models.TextField(blank=True, verbose_name="توضیح کوتاه")),
                ("body", models.TextField(verbose_name="متن پرامپت")),
                ("language", models.CharField(default="fa", max_length=10, verbose_name="زبان")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")],
                        default="published",
                        max_length=12,
                        verbose_name="وضعیت",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="تاریخ ویرایش")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_prompt_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_prompt_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="آخرین ویرایش توسط",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
                "verbose_name": "پرامپت",
                "verbose_name_plural": "پرامپت‌ها",
            },
        ),
        migrations.CreateModel(
            name="WritingRuleSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "key",
                    models.SlugField(
                        allow_unicode=True,
                        help_text="کلید ثابت (مثلاً: educational-article-rules)",
                        max_length=80,
                        unique=True,
                        verbose_name="کلید",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("description", models.TextField(blank=True, verbose_name="توضیح کوتاه")),
                ("body", models.TextField(verbose_name="قوانین/راهنما")),
                (
                    "scenario",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="مثال: educational, analysis, howto ...",
                        max_length=50,
                        verbose_name="سناریو",
                    ),
                ),
                (
                    "applies_to_content_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='لیست مانند: ["short_news","post","article"] (خالی یعنی همه)',
                        verbose_name="محدود به نوع محتوا",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="عدد کمتر = پیشنهاد بالاتر در لیست",
                        verbose_name="اولویت",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")],
                        default="published",
                        max_length=12,
                        verbose_name="وضعیت",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="تاریخ ویرایش")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_writing_rules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_writing_rules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="آخرین ویرایش توسط",
                    ),
                ),
                (
                    "default_prompt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_rulesets",
                        to="editorial.prompttemplate",
                        verbose_name="پرامپت پیشنهادی",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "title"],
                "verbose_name": "قانون/راهنما",
                "verbose_name_plural": "قوانین/راهنماها",
            },
        ),
        migrations.AddField(
            model_name="writingruleset",
            name="categories",
            field=models.ManyToManyField(blank=True, related_name="writing_rules", to="taxonomy.category", verbose_name="دسته‌ها"),
        ),
        migrations.AddField(
            model_name="writingruleset",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="writing_rules", to="taxonomy.tag", verbose_name="تگ‌ها"),
        ),
        migrations.AddField(
            model_name="writingruleset",
            name="prompts",
            field=models.ManyToManyField(blank=True, related_name="rule_sets", to="editorial.prompttemplate", verbose_name="پرامپت‌های مرتبط"),
        ),
        migrations.AddIndex(
            model_name="prompttemplate",
            index=models.Index(fields=["key"], name="editorial_pr_key_idx"),
        ),
        migrations.AddIndex(
            model_name="prompttemplate",
            index=models.Index(fields=["status", "is_active"], name="editorial_pr_state_idx"),
        ),
        migrations.AddIndex(
            model_name="prompttemplate",
            index=models.Index(fields=["-updated_at"], name="editorial_pr_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="writingruleset",
            index=models.Index(fields=["key"], name="editorial_wr_key_idx"),
        ),
        migrations.AddIndex(
            model_name="writingruleset",
            index=models.Index(fields=["scenario", "status", "is_active"], name="editorial_wr_state_idx"),
        ),
        migrations.AddIndex(
            model_name="writingruleset",
            index=models.Index(fields=["-updated_at"], name="editorial_wr_updated_idx"),
        ),
    ]
