from __future__ import annotations
# Generated by Django 5.2.8 on 2026-02-13 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_categories', models.ManyToManyField(blank=True, related_name='preferred_by_profiles', to='taxonomy.category')),
                ('preferred_entities', models.ManyToManyField(blank=True, related_name='preferred_by_profiles', to='entities.entity')),
                ('preferred_tags', models.ManyToManyField(blank=True, related_name='preferred_by_profiles', to='taxonomy.tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='accounts_us_user_id_806298_idx')],
            },
        ),
    ]
