from __future__ import annotations
# Generated by Django 5.2.8 on 2026-02-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['email', '-created_at'], name='accounts_em_email_35a1ad_idx'), models.Index(fields=['email', 'used_at', 'expires_at'], name='accounts_em_email_c46193_idx')],
            },
        ),
    ]
