from __future__ import annotations
# Generated by Django 5.2.8 on 2026-02-13 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anon_id', models.CharField(max_length=36, unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyArticleInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('bookmarks', models.PositiveIntegerField(default=0)),
                ('dwell_seconds', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_interactions', to='content.article')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_article_interactions', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_article_interactions', to='interactions.visitor')),
            ],
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['anon_id'], name='interaction_anon_id_a7ebc5_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['user'], name='interaction_user_id_3b5293_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['last_seen'], name='interaction_last_se_ee720f_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyarticleinteraction',
            index=models.Index(fields=['user', 'date'], name='interaction_user_id_66351f_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyarticleinteraction',
            index=models.Index(fields=['visitor', 'date'], name='interaction_visitor_8b14f4_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyarticleinteraction',
            index=models.Index(fields=['article', 'date'], name='interaction_article_df24ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyarticleinteraction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('user__isnull', False), ('visitor__isnull', True)), models.Q(('user__isnull', True), ('visitor__isnull', False)), _connector='OR'), name='interaction_user_xor_visitor'),
        ),
        migrations.AddConstraint(
            model_name='dailyarticleinteraction',
            constraint=models.UniqueConstraint(fields=('date', 'visitor', 'article'), name='uniq_daily_interaction_visitor'),
        ),
        migrations.AddConstraint(
            model_name='dailyarticleinteraction',
            constraint=models.UniqueConstraint(fields=('date', 'user', 'article'), name='uniq_daily_interaction_user'),
        ),
    ]
