from __future__ import annotations
# Generated by Django 5.2.8 on 2026-02-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='visitor',
            name='interaction_anon_id_a7ebc5_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitor',
            name='interaction_user_id_3b5293_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitor',
            name='interaction_last_se_ee720f_idx',
        ),
    ]
