from __future__ import annotations
# Generated by Django 5.2.8 on 2026-02-13 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_remove_visitor_interaction_anon_id_a7ebc5_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyarticleinteraction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_article_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyarticleinteraction',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_article_interactions', to='interactions.visitor'),
        ),
    ]
