from __future__ import annotations
# Generated by Django 5.2.11 on 2026-02-19 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_articlecomment'),
        ('interactions', '0003_alter_dailyarticleinteraction_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserArticleState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('bookmarked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='content.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'liked_at'], name='interaction_user_id_a813f4_idx'), models.Index(fields=['user', 'bookmarked_at'], name='interaction_user_id_ebdc6c_idx'), models.Index(fields=['article', 'liked_at'], name='interaction_article_075c2a_idx'), models.Index(fields=['article', 'bookmarked_at'], name='interaction_article_16dce8_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'article'), name='uniq_user_article_state')],
            },
        ),
    ]
