from __future__ import annotations
# Generated by Django 5.2.8 on 2026-02-21 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_userarticlestate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='interaction_is_acti_b56c71_idx')],
            },
        ),
        migrations.CreateModel(
            name='PollQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('kind', models.CharField(choices=[('single', 'Single'), ('multi', 'Multi')], default='single', max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interactions.poll')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PollChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='interactions.pollquestion')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PollResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interactions.poll')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll_responses', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll_responses', to='interactions.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='PollAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interactions.pollchoice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interactions.pollquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interactions.pollresponse')),
            ],
        ),
        migrations.AddIndex(
            model_name='pollquestion',
            index=models.Index(fields=['poll', 'sort_order'], name='interaction_poll_id_dd94ea_idx'),
        ),
        migrations.AddIndex(
            model_name='pollchoice',
            index=models.Index(fields=['question', 'sort_order'], name='interaction_questio_bfa58a_idx'),
        ),
        migrations.AddIndex(
            model_name='pollresponse',
            index=models.Index(fields=['poll', 'created_at'], name='interaction_poll_id_4a461b_idx'),
        ),
        migrations.AddIndex(
            model_name='pollresponse',
            index=models.Index(fields=['user', 'created_at'], name='interaction_user_id_9466d9_idx'),
        ),
        migrations.AddIndex(
            model_name='pollresponse',
            index=models.Index(fields=['visitor', 'created_at'], name='interaction_visitor_029235_idx'),
        ),
        migrations.AddConstraint(
            model_name='pollresponse',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('user__isnull', False), ('visitor__isnull', True)), models.Q(('user__isnull', True), ('visitor__isnull', False)), _connector='OR'), name='poll_response_user_xor_visitor'),
        ),
        migrations.AddConstraint(
            model_name='pollresponse',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('poll', 'user'), name='uniq_poll_response_user'),
        ),
        migrations.AddConstraint(
            model_name='pollresponse',
            constraint=models.UniqueConstraint(condition=models.Q(('visitor__isnull', False)), fields=('poll', 'visitor'), name='uniq_poll_response_visitor'),
        ),
        migrations.AddIndex(
            model_name='pollanswer',
            index=models.Index(fields=['response', 'question'], name='interaction_respons_709127_idx'),
        ),
        migrations.AddIndex(
            model_name='pollanswer',
            index=models.Index(fields=['question', 'choice'], name='interaction_questio_63f88a_idx'),
        ),
        migrations.AddConstraint(
            model_name='pollanswer',
            constraint=models.UniqueConstraint(fields=('response', 'choice'), name='uniq_poll_answer_response_choice'),
        ),
    ]
