from __future__ import annotations
# Generated by ChatGPT on 2026-02-22

import django.db.models.deletion
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_article_video_thumbnail_article_video_url"),
        ("interactions", "0005_poll_pollquestion_pollchoice_pollresponse_pollanswer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleRating",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.PositiveSmallIntegerField(db_index=True, validators=[MinValueValidator(1), MaxValueValidator(5)])),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ratings", to="content.article")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="article_ratings", to=settings.AUTH_USER_MODEL)),
                ("visitor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="article_ratings", to="interactions.visitor")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["article", "created_at"], name="interaction_article__7c4d1d_idx"),
                    models.Index(fields=["user", "created_at"], name="interaction_user_id_6e5ef1_idx"),
                    models.Index(fields=["visitor", "created_at"], name="interaction_visitor_3d4f63_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="articlerating",
            constraint=models.CheckConstraint(
                check=((Q(("user__isnull", False)) & Q(("visitor__isnull", True))) | (Q(("user__isnull", True)) & Q(("visitor__isnull", False)))),
                name="article_rating_user_xor_visitor",
            ),
        ),
        migrations.AddConstraint(
            model_name="articlerating",
            constraint=models.UniqueConstraint(
                condition=Q(("user__isnull", False)),
                fields=("article", "user"),
                name="uniq_article_rating_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="articlerating",
            constraint=models.UniqueConstraint(
                condition=Q(("visitor__isnull", False)),
                fields=("article", "visitor"),
                name="uniq_article_rating_visitor",
            ),
        ),
    ]
