from __future__ import annotations
# Generated by Django 5.2.11 on 2026-02-21 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0006_article_rating'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='articlerating',
            new_name='interaction_article_ccb912_idx',
            old_name='interaction_article__7c4d1d_idx',
        ),
        migrations.RenameIndex(
            model_name='articlerating',
            new_name='interaction_user_id_5f9a5e_idx',
            old_name='interaction_user_id_6e5ef1_idx',
        ),
        migrations.RenameIndex(
            model_name='articlerating',
            new_name='interaction_visitor_8eab28_idx',
            old_name='interaction_visitor_3d4f63_idx',
        ),
    ]
