from __future__ import annotations
# Generated by Django 5.2.8 on 2026-02-13 09:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('short_news', 'Short News'), ('post', 'Post'), ('article', 'Article')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=280, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('language', models.CharField(default='fa', max_length=10)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='articles/hero/%Y/%m/')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=180)),
                ('seo_description', models.TextField(blank=True)),
                ('canonical_path', models.CharField(blank=True, max_length=500)),
                ('meta_robots', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('weight', models.FloatField(default=1.0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_categories', to='content.article')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_articles', to='taxonomy.category')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(related_name='articles', through='content.ArticleCategory', to='taxonomy.category'),
        ),
        migrations.CreateModel(
            name='ArticleEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main', 'Main'), ('mentioned', 'Mentioned'), ('author', 'Author'), ('target', 'Target')], default='mentioned', max_length=20)),
                ('importance', models.FloatField(default=1.0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_entities', to='content.article')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entity_articles', to='entities.entity')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='entities',
            field=models.ManyToManyField(related_name='articles', through='content.ArticleEntity', to='entities.entity'),
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_tags', to='content.article')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tag_articles', to='taxonomy.tag')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', through='content.ArticleTag', to='taxonomy.tag'),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('official', 'Official'), ('blog', 'Blog'), ('paper', 'Paper'), ('social', 'Social'), ('other', 'Other')], default='other', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='content_sou_is_acti_759658_idx'), models.Index(fields=['type'], name='content_sou_type_0bf9c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArticleSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('note', models.TextField(blank=True)),
                ('confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_sources', to='content.article')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_articles', to='content.source')),
            ],
        ),
        migrations.AddConstraint(
            model_name='articlecategory',
            constraint=models.UniqueConstraint(fields=('article', 'category'), name='uniq_article_category'),
        ),
        migrations.AddConstraint(
            model_name='articlecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('article',), name='uniq_primary_category_per_article'),
        ),
        migrations.AddConstraint(
            model_name='articleentity',
            constraint=models.UniqueConstraint(fields=('article', 'entity', 'role'), name='uniq_article_entity_role'),
        ),
        migrations.AddConstraint(
            model_name='articletag',
            constraint=models.UniqueConstraint(fields=('article', 'tag'), name='uniq_article_tag'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'published_at'], name='content_art_status_4645e7_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['content_type', 'published_at'], name='content_art_content_832364_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='content_art_slug_d82f31_idx'),
        ),
        migrations.AddConstraint(
            model_name='articlesource',
            constraint=models.UniqueConstraint(fields=('article', 'source', 'original_url'), name='uniq_article_source_url'),
        ),
    ]
