from __future__ import annotations
# Generated by Django 5.2.8 on 2026-02-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='content_art_slug_d82f31_idx',
        ),
    ]
