from __future__ import annotations
# Generated by Django 5.2.8 on 2026-02-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_article_content_art_slug_d82f31_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_team_pick',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
