from __future__ import annotations
# Generated by Django 5.2.8 on 2026-02-14 03:58

from django.db import migrations, models


def normalize_legacy_statuses(apps, schema_editor):
    Article = apps.get_model("content", "Article")
    Article.objects.filter(status__in=["review", "archived"]).update(status="draft")


def reverse_normalize_legacy_statuses(apps, schema_editor):
    # Legacy statuses are collapsed into draft and cannot be reliably restored.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_article_is_team_pick'),
    ]

    operations = [
        migrations.RunPython(normalize_legacy_statuses, reverse_normalize_legacy_statuses),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
    ]
