from __future__ import annotations
# Generated by Django 5.2.8 on 2026-02-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='hero_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
