from __future__ import annotations
# Generated by Django 5.2.8 on 2026-02-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_articlecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video_thumbnail',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
