from __future__ import annotations
# Generated by ChatGPT on 2026-02-22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_article_video_thumbnail_article_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlecomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="content.articlecomment",
            ),
        ),
        migrations.AddIndex(
            model_name="articlecomment",
            index=models.Index(fields=["article", "parent", "is_visible", "created_at"], name="content_art_article__a2b4b9_idx"),
        ),
    ]
