from __future__ import annotations
# Generated by Django 5.2.11 on 2026-02-21 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_articlecomment_parent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='articlecomment',
            new_name='content_art_article_c4cd1d_idx',
            old_name='content_art_article__a2b4b9_idx',
        ),
    ]
