from __future__ import annotations
# Generated by ChatGPT on 2026-02-26

from django.db import migrations, models
import apps.content.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_rename_content_art_article__a2b4b9_idx_content_art_article_c4cd1d_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='goals',
            field=models.JSONField(blank=True, default=list, validators=[apps.content.models.validate_article_goals]),
        ),
    ]
