from __future__ import annotations
# Generated by ChatGPT on 2026-02-27

from django.db import migrations, models


def dedupe_main_entities(apps, schema_editor):
    ArticleEntity = apps.get_model('content', 'ArticleEntity')
    db_alias = schema_editor.connection.alias

    from django.db.models import Count

    duplicate_article_ids = (
        ArticleEntity.objects.using(db_alias)
        .filter(role='main')
        .values('article_id')
        .annotate(main_count=Count('id'))
        .filter(main_count__gt=1)
        .values_list('article_id', flat=True)
    )

    for article_id in duplicate_article_ids:
        main_rows = list(
            ArticleEntity.objects.using(db_alias)
            .filter(article_id=article_id, role='main')
            .order_by('-importance', 'id')
        )

        for row in main_rows[1:]:
            has_mentioned = ArticleEntity.objects.using(db_alias).filter(
                article_id=article_id,
                entity_id=row.entity_id,
                role='mentioned',
            ).exists()
            if has_mentioned:
                row.delete(using=db_alias)
            else:
                ArticleEntity.objects.using(db_alias).filter(id=row.id).update(role='mentioned')


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_article_goals'),
    ]

    operations = [
        migrations.RunPython(dedupe_main_entities, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='articleentity',
            constraint=models.UniqueConstraint(
                fields=('article',),
                condition=models.Q(role='main'),
                name='uniq_main_entity_per_article',
            ),
        ),
    ]
