from __future__ import annotations
# Generated by Django 5.2.11 on 2026-02-27 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_main_entity_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleentity',
            name='importance',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(3.0)]),
        ),
    ]
