from __future__ import annotations
# Generated by Django 5.2.8 on 2026-02-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('company', 'Company'), ('person', 'Person'), ('model', 'Model'), ('product', 'Product'), ('lab', 'Lab'), ('dataset', 'Dataset'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(allow_unicode=True, max_length=180, unique=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('seo_title', models.CharField(blank=True, max_length=180)),
                ('seo_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_indexable', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['type', 'slug'], name='entities_en_type_e96be4_idx'), models.Index(fields=['name'], name='entities_en_name_70a53e_idx'), models.Index(fields=['is_active'], name='entities_en_is_acti_051fb8_idx'), models.Index(fields=['is_indexable'], name='entities_en_is_inde_5ee2c9_idx')],
                'constraints': [models.UniqueConstraint(fields=('type', 'name'), name='uniq_entity_type_name')],
            },
        ),
    ]
