from __future__ import annotations
# Generated by Django 5.2.8 on 2026-02-21 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('company', 'Company'), ('model', 'Model')], max_length=20)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['is_active', 'kind'], name='entities_ra_is_acti_86edaa_idx')],
            },
        ),
        migrations.CreateModel(
            name='RankingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('score', models.FloatField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='entities.rankinglist')),
            ],
            options={
                'ordering': ['rank', 'id'],
                'indexes': [models.Index(fields=['ranking', 'rank'], name='entities_ra_ranking_d484d0_idx')],
                'constraints': [models.UniqueConstraint(fields=('ranking', 'rank'), name='uniq_ranking_entry_rank')],
            },
        ),
    ]
