from __future__ import annotations
# Generated by Django 5.2.8 on 2026-02-13 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('signals', models.JSONField(blank=True, default=dict)),
                ('algo_version', models.CharField(default='v1', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_primary', to='content.article')),
                ('article_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_secondary', to='content.article')),
            ],
            options={
                'indexes': [models.Index(fields=['article_a', '-score'], name='relations_a_article_ebc62b_idx'), models.Index(fields=['article_b', '-score'], name='relations_a_article_2a7910_idx'), models.Index(fields=['-score'], name='relations_a_score_c9c1da_idx')],
                'constraints': [models.UniqueConstraint(fields=('article_a', 'article_b'), name='uniq_article_relation_pair'), models.CheckConstraint(check=models.Q(('article_a', models.F('article_b')), _negated=True), name='article_relation_no_self_link')],
            },
        ),
    ]
