from __future__ import annotations
# Generated by Django 5.2.8 on 2026-02-13 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(allow_unicode=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('seo_title', models.CharField(blank=True, max_length=180)),
                ('seo_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_indexable', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['slug'], name='taxonomy_ta_slug_a90815_idx'), models.Index(fields=['is_active'], name='taxonomy_ta_is_acti_a74507_idx'), models.Index(fields=['is_indexable'], name='taxonomy_ta_is_inde_11f164_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(allow_unicode=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('seo_title', models.CharField(blank=True, max_length=180)),
                ('seo_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_indexable', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='taxonomy.category')),
            ],
            options={
                'ordering': ['order', 'title'],
                'indexes': [models.Index(fields=['slug'], name='taxonomy_ca_slug_79d2b3_idx'), models.Index(fields=['parent'], name='taxonomy_ca_parent__1d5774_idx'), models.Index(fields=['is_active'], name='taxonomy_ca_is_acti_7cbdeb_idx'), models.Index(fields=['is_indexable'], name='taxonomy_ca_is_inde_54aa9c_idx')],
            },
        ),
    ]
