from __future__ import annotations
# Generated by Django 5.2.8 on 2026-02-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='taxonomy_ca_slug_79d2b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='taxonomy_ca_parent__1d5774_idx',
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='taxonomy_ta_slug_a90815_idx',
        ),
    ]
